# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'CNN-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'CNN-flutter-lib'
  # Pods for CNN-iOS

end
